# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  NERT Server:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:4.0.3

    # Change this directory to your project's directory.
    working_directory: ~/nert

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-server-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-server-

      - run: yarn

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-server-{{ checksum "package.json" }}

      # Run typescript
      - run: yarn tsc
      # run tests!
      - run: yarn jest

  NERT Client:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    # Change this directory to your project's directory.
    working_directory: ~/nert

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-client-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-client-

      - run:
          name: Install client dependencies
          command: cd client && yarn

      - save_cache:
          paths:
            - ./client/node_modules
          key: dependency-cache-client-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run client tests
          command: cd client && yarn test

workflows:
  version: 2
  Test Server and Client:
    jobs:
      - NERT Client
      - NERT Server
